name: spaceinvaders
version: 0.0.1
description: Material Design Lite 'MDL Text-Only Template'
author: <Mike Mitterer> <office@mikemitterer.at>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  mdl: '>=1.0.0 <2.0.0'

  logging: any
  logging_handlers: any
  console_log_handler: any

  di: any

dev_dependencies:
  test: ^0.12.0
  grinder: ^0.8.0

transformers:
  - di