name: spaceinvaders
version: 1.1.0
description: Space-Invaders built with Material Design Lite 4 Dart
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-space-invaders

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  browser: ^0.10.0

  mdl: ^2.0.0
    # ^1.0.0
    # path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

dev_dependencies:
  test: any
  grinder: any
  sitegen: any

transformers:

  - $dart2js:
      commandLineOptions: [--enable-experimental-mirrors]
      checked: true
      minify: false
      sourceMaps: true