name: spaceinvaders
version: 1.0.1
description: Space-Invaders built with Material Design Lite 4 Dart
author: <Mike Mitterer> <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-space-invaders

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: ^0.10.0

  mdl: '>=1.0.0 <2.0.0'
    #path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0

  di: ^3.3.0

dev_dependencies:
  test: any
  grinder: any

transformers:
  - di