name: mdl_arcade_button_sample
description: Material Design Lite 'Arcade-Button' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

dependencies:
  browser: any

  intl: any
  args: any
  validate: any
  browser_detect: any

  logging: any
  logging_handlers: any
  console_log_handler: any
  #  path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  spaceinvaders:
    path: ../..

  mdl: ^1.0.0

  di: any

transformers:
  - di

#  - $dart2js:
#      minify: false
#      sourceMaps: true



