name: mdl_arcade_button_sample
description: Material Design Lite 'Arcade-Button' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  intl: any
  args: any
  validate: any

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0

  spaceinvaders:
    path: ../..

  m4d_core: '>=0.1.0 <1.0.0'
    # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_core

  m4d_components: '>=0.1.0 <1.0.0'
    # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_components

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  
  sass_builder: any



